const movies = [
  {
    id: 1,
    title: 'Kingsglaive',
    subtitle: 'Final Fantasy XV',
    storyline: "King Regis, who oversees the land of Lucis, commands his army of soldiers to protect the kingdom from the Niflheim empire's plans to steal the sacred crystal.",
    rating: 4.5,
    imagePath: 'https://miro.medium.com/max/3200/0*FwNuPSn7wUAD-idz.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    id: 2,
    title: 'Final Fantasy',
    subtitle: 'Spirits Within',
    storyline: 'A scientist makes a last stand on Earth with the help of a ragtag team of soldiers against an invasion of alien phantoms.',
    rating: 4.5,
    imagePath: 'https://lh3.googleusercontent.com/proxy/4JR0NZnAjUIT3HMB8fUY3Szu8Loj6LTWuiRcgghQ3VU_sXWz63YWYAQh-GV01WBHLe0ZiQ0gafTeYQB3E4ZbJL4Gmgf9bJiwLTiezPyRGOM_jxd16AKU6oFz7PNXf6j68TE-G7sr',
    bookmarked: false,
    genre: 'fantasy',
  },
  {
    id: 3,
    title: 'Ghost In The Shell',
    subtitle: 'Ghost In The Shell',
    storyline: 'A hacker known as the Puppet Master is hunted by a female cyborg cop and her partner. This film is a revised version of Ghost in the Shell (1995).',
    rating: 5,
    imagePath: 'https://steamcdn-a.akamaihd.net/steam/apps/589900/capsule_616x353.jpg?t=1491508965',
    bookmarked: false,
    genre: 'comedy',
  },
  {
    id: 4,
    title: 'Appleseed Alpha',
    subtitle: 'Appleseed Alpha',
    storyline: "A young female soldier Deunan and her cyborg partner Briareos survive through the post World War 3 apocalyptic New York in search of human's future hope, the legendary city of Olympus.",
    rating: 3.8,
    imagePath: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjvfDAGKNMskXQIeJXAVPUDkmtxbJbM692ZQ&usqp=CAU',
    bookmarked: true,
    genre: 'action',
  },
  {
    id: 5,
    title: 'Resident Evil',
    subtitle: 'Vendetta',
    storyline: 'Chris Redfield enlists the help of Leon S. Kennedy and Rebecca Chambers to stop a death merchant, with a vengeance, from spreading a deadly virus in New York.',
    rating: 4.2,
    imagePath: 'https://www.superamiches.com/wp-content/uploads/2017/06/maxresdefault-2.jpg',
    bookmarked: true,
    genre: 'fantasy',
  },
];

export default movies;
